title: "김민혁 이력서"
description: "동양미래대학교 소프트웨어공학과 3학년 개발자 포트폴리오"
author: "김민혁"
email: your@email.com
github_username: loniskr

theme: jekyll-theme-slate

# 옵션 (필요하면 활성화)
# show_downloads: true
# google_analytics: UA-XXXXXXXXX-X
